import { useState } from "react";
import type { Language } from "./content";

const asset = (path: string) => `${import.meta.env.BASE_URL}${path}`;
type GoalId = "composition" | "alpha" | "structure" | "differential" | "relations";
type AnalysisGoal = { id: GoalId; number: string; nav: string; title: string; question: string; description: string; observe: string[]; methods: string[]; images: { src: string; label: string }[]; module: string };

function Eyebrow({ children }: { children: React.ReactNode }) {
  return <p className="eyebrow"><span />{children}</p>;
}

export default function AnalysesPageV2({ language }: { language: Language }) {
  const [activeGoal, setActiveGoal] = useState<GoalId>("composition");
  const c = language === "fr" ? {
    heroK: "Analyses dans BarCodeR",
    heroT: <><span>Exploration et analyse interactives</span><em>de données de métabarcoding.</em></>,
    heroP: "De la description des communautés aux comparaisons entre datasets, BarCodeR réunit des analyses paramétrables et des visualisations réactives dans un même environnement.",
    orientK: "Que cherchez-vous à comprendre ?", orientT: "Couvrez un large spectre de questions scientifiques",
    qualities: [["Simple", "Des choix lisibles pour configurer rapidement chaque analyse."], ["Interactif", "Des figures manipulables pour explorer les résultats en profondeur."], ["Réactif", "Les résultats se mettent à jour selon les paramètres retenus."]],
    canObserve: "Ce que vous pouvez examiner (et bien plus encore)", available: "Analyses disponibles (non exhaustives)", documentation: "En savoir plus sur ces analyses", figureLabel: "Aperçus des analyses",
    centralK: "Une lecture construite autour du résultat", centralT: "Une figure centrale, appuyée par des figures diagnostiques.", centralP: "Chaque analyse met en avant un résultat principal. Lorsque la méthode l’exige, des figures et indicateurs complémentaires permettent d’en évaluer la qualité, les hypothèses et la robustesse avant l’interprétation.",
    centralItems: [["Figure centrale", "Le résultat principal répond directement à la question scientifique posée."], ["Diagnostics associés", "Les contrôles utiles sont présentés à proximité du résultat qu’ils documentent."], ["Lecture cohérente", "Résultat, paramètres et diagnostics forment un ensemble interprétable."]],
    centralMain: "Figure centrale", centralDiagnostic: "Diagnostic statistique", centralQuality: "Contrôle de qualité",
    compareK: "Analyses intra- et inter-datasets", compareT: "Explorer chaque dataset, puis les mettre en relation.", compareP: "BarCodeR permet d’analyser un dataset isolément, plusieurs datasets en parallèle et, lorsque les méthodes le permettent, de comparer directement leurs structures ou leurs résultats.",
    compareModes: [["INTRA", "Un dataset à la fois", "Décrire et tester chaque objet phyloseq dans son propre contexte."], ["INTER", "Plusieurs datasets réunis", "Mettre leurs résultats en regard ou les comparer directement lorsque la méthode le permet."]],
    compareCards: [["Au sein d’un dataset", "Décrire, explorer et tester les structures propres à chaque objet phyloseq."], ["En parallèle", "Appliquer une même lecture à plusieurs datasets réunis dans un projet."], ["Entre datasets", "Comparer marqueurs, domaines, distances ou configurations avec les méthodes compatibles."]],
    reproK: "Reproductibilité", reproT: "Chaque résultat reste relié à ce qui l’a produit.", reproP: "La reproductibilité ne se limite pas à conserver une image finale. Dans BarCodeR, une analyse sauvegardée reste associée au dataset et à sa version, aux paramètres retenus, aux diagnostics générés et au code R lorsque celui-ci est disponible. Le projet conserve ainsi le contexte nécessaire pour comprendre comment le résultat a été obtenu, relancer l’analyse dans les mêmes conditions, comparer plusieurs essais ou transmettre un travail interprétable à une autre personne.",
    reproFlow: ["Dataset versionné", "Paramètres", "Analyse et diagnostics", "Figure sauvegardée", "Historique et code R"],
    reproCards: [["Retrouver", "Identifier le dataset, sa version et les réglages utilisés pour produire chaque résultat sauvegardé."], ["Répéter", "Relancer l’analyse avec les mêmes paramètres ou repartir d’un état antérieur sans reconstruire le parcours de mémoire."], ["Comparer", "Conserver plusieurs essais pour confronter les choix de préparation, de calcul ou de représentation."], ["Transmettre", "Exporter le projet avec son contexte afin qu’un autre utilisateur puisse reprendre et comprendre le travail."]]
  } : {
    heroK: "Analyses in BarCodeR",
    heroT: <><span>Interactive exploration and analysis</span><em>of metabarcoding data.</em></>,
    heroP: "From community description to comparisons across datasets, BarCodeR brings configurable analyses and responsive visualisations together in one environment.",
    orientK: "What are you trying to understand?", orientT: "Address a broad spectrum of scientific questions",
    qualities: [["Simple", "Clear choices make every analysis quick to configure."], ["Interactive", "Manipulable figures support in-depth result exploration."], ["Responsive", "Results update according to the selected parameters."]],
    canObserve: "What you can examine (and much more)", available: "Available analyses (non-exhaustive)", documentation: "Learn more about these analyses", figureLabel: "Analysis previews",
    centralK: "A result-centred interpretation", centralT: "One central figure, supported by diagnostic figures.", centralP: "Each analysis foregrounds one main result. When required by the method, complementary figures and indicators help assess quality, assumptions and robustness before interpretation.",
    centralItems: [["Central figure", "The main result directly addresses the scientific question."], ["Associated diagnostics", "Relevant checks are shown close to the result they document."], ["Coherent interpretation", "Result, parameters and diagnostics form one interpretable whole."]],
    centralMain: "Central figure", centralDiagnostic: "Statistical diagnostic", centralQuality: "Quality check",
    compareK: "Within- and between-dataset analyses", compareT: "Explore each dataset, then relate them.", compareP: "BarCodeR can analyse one dataset, several datasets in parallel and, where supported by the methods, directly compare their structures or results.",
    compareModes: [["WITHIN", "One dataset at a time", "Describe and test each phyloseq object in its own context."], ["BETWEEN", "Several datasets together", "Place their results side by side or compare them directly when supported by the method."]],
    compareCards: [["Within one dataset", "Describe, explore and test structures specific to each phyloseq object."], ["In parallel", "Apply the same reading to several datasets gathered in one project."], ["Across datasets", "Compare markers, domains, distances or configurations with compatible methods."]],
    reproK: "Reproducibility", reproT: "Every result remains connected to what produced it.", reproP: "Reproducibility is not limited to keeping a final image. In BarCodeR, a saved analysis remains associated with its dataset and version, selected parameters, generated diagnostics and R code when available. The project therefore retains the context required to understand how a result was obtained, rerun the analysis under the same conditions, compare several attempts or transfer interpretable work to another person.",
    reproFlow: ["Versioned dataset", "Parameters", "Analysis and diagnostics", "Saved figure", "History and R code"],
    reproCards: [["Retrieve", "Identify the dataset, its version and the settings used to produce each saved result."], ["Repeat", "Rerun an analysis with the same parameters or resume from an earlier state without rebuilding the journey from memory."], ["Compare", "Keep several attempts to compare preparation, computation or representation choices."], ["Transfer", "Export the project with its context so another user can resume and understand the work."]]
  };

  const goals: AnalysisGoal[] = language === "fr" ? [
    { id: "composition", number: "01", nav: "Composition", title: "Décrire la composition des communautés", question: "Quels taxons composent les communautés et comment sont-ils répartis ?", description: "Explorez la composition intra-dataset à différents rangs taxonomiques, puis comparez les taxons dominants, partagés ou spécifiques entre plusieurs datasets.", observe: ["Taxons dominants par échantillon, groupe ou dataset", "Taxons partagés et spécifiques au sein ou entre datasets", "Résolution et complétude taxonomiques", "Visualisation de la composition taxonomique dans un arbre ou un Heat Tree"], methods: ["Barplots", "Venn", "UpSet", "Heat Tree", "Arbres phylogénétiques", "Qualité taxonomique"], images: [{ src: "app-previews/barplot.png", label: "Barplots" }, { src: "app-previews/heat_tree.png", label: "Heat Tree" }, { src: "app-previews/diagramme_venn.png", label: "Venn / UpSet" }], module: "Exploration" },
    { id: "alpha", number: "02", nav: "Diversité", title: "Étudier la diversité au sein des échantillons", question: "La richesse ou la diversité intra-échantillon varie-t-elle entre les groupes ou les datasets ?", description: "Calculez plusieurs dimensions complémentaires de la diversité, visualisez-les simplement et comparez leurs distributions au sein d’un dataset ou entre plusieurs datasets.", observe: ["Richesse observée et estimée", "Diversité tenant compte des abondances", "Diversité phylogénétique si un arbre est disponible", "Comparaisons intra- et inter-datasets"], methods: ["Observed", "Chao1", "ACE", "Shannon", "Simpson", "Inverse Simpson", "Fisher", "Faith PD"], images: [{ src: "app-previews/alpha_diversite.png", label: "Alpha-diversité" }, { src: "app-previews/qualite_assignation_taxonomique.png", label: "Diagnostics" }], module: "Exploration" },
    { id: "structure", number: "03", nav: "Structure", title: "Comparer la structure des communautés", question: "Les communautés s’organisent-elles selon une condition ou une variable environnementale ?", description: "Représentez interactivement les distances entre échantillons et datasets, évaluez l’ordination et testez les différences de position et de dispersion.", observe: ["Organisation globale des échantillons dans chaque dataset", "Concordance des structures entre datasets", "Variables associées aux principaux gradients", "Différences de centroïdes et de dispersion"], methods: ["PCA", "PCoA", "NMDS", "CCA", "RDA", "dbRDA", "PERMANOVA", "PERMDISP"], images: [{ src: "app-previews/ordinations.png", label: "Ordinations" }, { src: "app-previews/permanova_dispersion.png", label: "PERMANOVA / dispersion" }], module: "Analyse" },
    { id: "differential", number: "04", nav: "Taxons associés", title: "Identifier les taxons associés à une condition", question: "Quels taxons présentent une association robuste avec le facteur étudié ?", description: "Appliquez simplement un ou plusieurs moteurs à chaque dataset, ajustez les paramètres de façon réactive puis confrontez la significativité et la direction des effets.", observe: ["Taxons significativement associés dans chaque dataset", "Direction de l’association", "Résultats propres à une méthode", "Concordances entre méthodes ou datasets"], methods: ["ANCOM-BC2", "LinDA", "ALDEx2", "corncob", "MaAsLin 3"], images: [{ src: "app-previews/analyses_differentielles.png", label: "Analyses différentielles" }, { src: "app-previews/heat_tree.png", label: "Résultats taxonomiques" }], module: "Analyse" },
    { id: "relations", number: "05", nav: "Relations", title: "Explorer des relations, regroupements et concordances", question: "Plusieurs datasets ou groupes de taxons révèlent-ils une organisation commune ?", description: "Comparez des matrices appariées entre datasets, explorez des regroupements ou construisez des réseaux d’associations grâce à des paramétrages interactifs et réactifs.", observe: ["Concordance entre plusieurs marqueurs ou datasets", "Échantillons responsables d’accords ou désaccords", "Regroupements d’échantillons ou de taxons", "Associations statistiques et stabilité des arêtes"], methods: ["Mantel", "Procrustes", "PROTEST", "Co-inertie", "MCOA", "Clustering", "SPIEC-EASI", "SparCC", "Proportionnalité"], images: [{ src: "app-previews/comparaison_matrices.png", label: "Comparaison de matrices" }, { src: "app-previews/clustering.png", label: "Clustering" }], module: "Analyse" }
  ] : [
    { id: "composition", number: "01", nav: "Composition", title: "Describe community composition", question: "Which taxa compose the communities and how are they distributed?", description: "Explore within-dataset composition across taxonomic ranks, then compare dominant, shared or specific taxa across datasets.", observe: ["Dominant taxa by sample, group or dataset", "Shared and specific taxa within or across datasets", "Taxonomic resolution and completeness", "Taxonomic composition displayed in a tree or Heat Tree"], methods: ["Bar plots", "Venn", "UpSet", "Heat Tree", "Phylogenetic trees", "Taxonomic quality"], images: [{ src: "app-previews/barplot.png", label: "Bar plots" }, { src: "app-previews/heat_tree.png", label: "Heat Tree" }, { src: "app-previews/diagramme_venn.png", label: "Venn / UpSet" }], module: "Exploration" },
    { id: "alpha", number: "02", nav: "Diversity", title: "Study diversity within samples", question: "Does within-sample richness or diversity vary among groups or datasets?", description: "Calculate complementary dimensions of diversity, visualise them simply and compare distributions within one dataset or across several datasets.", observe: ["Observed and estimated richness", "Abundance-aware diversity", "Phylogenetic diversity when a tree is available", "Within- and between-dataset comparisons"], methods: ["Observed", "Chao1", "ACE", "Shannon", "Simpson", "Inverse Simpson", "Fisher", "Faith PD"], images: [{ src: "app-previews/alpha_diversite.png", label: "Alpha diversity" }, { src: "app-previews/qualite_assignation_taxonomique.png", label: "Diagnostics" }], module: "Exploration" },
    { id: "structure", number: "03", nav: "Structure", title: "Compare community structure", question: "Are communities organised according to a condition or environmental variable?", description: "Interactively represent distances among samples and datasets, assess ordination and test differences in location and dispersion.", observe: ["Overall sample organisation in each dataset", "Structural agreement across datasets", "Variables associated with main gradients", "Centroid and dispersion differences"], methods: ["PCA", "PCoA", "NMDS", "CCA", "RDA", "dbRDA", "PERMANOVA", "PERMDISP"], images: [{ src: "app-previews/ordinations.png", label: "Ordinations" }, { src: "app-previews/permanova_dispersion.png", label: "PERMANOVA / dispersion" }], module: "Analysis" },
    { id: "differential", number: "04", nav: "Associated taxa", title: "Identify taxa associated with a condition", question: "Which taxa show a robust association with the studied factor?", description: "Apply one or several engines to each dataset, adjust parameters responsively and compare significance and effect direction.", observe: ["Significantly associated taxa in each dataset", "Direction of association", "Method-specific results", "Agreement among methods or datasets"], methods: ["ANCOM-BC2", "LinDA", "ALDEx2", "corncob", "MaAsLin 3"], images: [{ src: "app-previews/analyses_differentielles.png", label: "Differential analyses" }, { src: "app-previews/heat_tree.png", label: "Taxonomic results" }], module: "Analysis" },
    { id: "relations", number: "05", nav: "Relationships", title: "Explore relationships, groups and agreement", question: "Do several datasets or taxon groups reveal a shared organisation?", description: "Compare matched matrices across datasets, explore groupings or build association networks through interactive, responsive settings.", observe: ["Agreement across markers or datasets", "Samples responsible for agreement or disagreement", "Sample or taxon groupings", "Statistical associations and edge stability"], methods: ["Mantel", "Procrustes", "PROTEST", "Co-inertia", "MCOA", "Clustering", "SPIEC-EASI", "SparCC", "Proportionality"], images: [{ src: "app-previews/comparaison_matrices.png", label: "Matrix comparison" }, { src: "app-previews/clustering.png", label: "Clustering" }], module: "Analysis" }
  ];

  const selected = goals.find(goal => goal.id === activeGoal) || goals[0];
  const guidePath = asset(`documentation/${language}/analyse/guides-methodologiques.html`);

  return <main className="analysis-v2-page">
    <section className="analysis-v2-hero"><div className="page-width">
      <header className="analysis-v2-hero-copy reveal"><Eyebrow>{c.heroK}</Eyebrow><h1>{c.heroT}</h1><p className="lead">{c.heroP}</p></header>
      <div className="analysis-v2-mosaic reveal delay-1">{[["app-previews/ordinations.png", "Ordinations"], ["app-previews/alpha_diversite.png", "Alpha-diversité"], ["app-previews/heat_tree.png", "Heat Tree"], ["app-previews/analyses_differentielles.png", "Analyses différentielles"], ["app-previews/comparaison_matrices.png", "Inter-datasets"], ["app-previews/clustering.png", "Clustering"]].map(([src, label], index) => <figure className={`mosaic-${index + 1}`} key={src}><img src={asset(src)} alt="" /><figcaption>{label}</figcaption></figure>)}</div>
    </div></section>

    <section className="analysis-v2-orient page-width" id="analysis-v2-orient">
      <div className="analysis-v2-orient-heading reveal"><Eyebrow>{c.orientK}</Eyebrow><h2>{c.orientT}</h2></div>
      <div className="analysis-v2-qualities reveal">{c.qualities.map(([title, text]) => <article key={title}><span>✦</span><div><b>{title}</b><p>{text}</p></div></article>)}</div>
      <div className="analysis-v2-tabs reveal" role="tablist">{goals.map(goal => <button type="button" role="tab" aria-selected={activeGoal === goal.id} className={activeGoal === goal.id ? "active" : ""} onClick={() => setActiveGoal(goal.id)} key={goal.id}><span>{goal.number}</span><b>{goal.nav}</b><i>→</i></button>)}</div>
      <article className="analysis-v2-goal" id="analysis-v2-goal" key={selected.id}>
        <div className="analysis-v2-goal-copy"><small>{selected.module}</small><h3>{selected.title}</h3><p className="analysis-v2-question">{selected.question}</p><p>{selected.description}</p><div className="analysis-v2-observe"><b>{c.canObserve}</b><ul>{selected.observe.map(item => <li key={item}>{item}</li>)}</ul></div><div className="analysis-v2-methods"><b>{c.available}</b><div>{selected.methods.map(method => <span key={method}>{method}</span>)}</div></div><nav><a href={guidePath} target="_blank" rel="noreferrer">{c.documentation}<span>↗</span></a></nav></div>
        <div className={`analysis-v2-goal-figures figures-${selected.images.length}`}><small>{c.figureLabel}</small>{selected.images.map((image, index) => <figure className={`figure-${index + 1}`} key={image.src}><img src={asset(image.src)} alt={image.label} /><figcaption><span>✦</span>{image.label}</figcaption></figure>)}</div>
      </article>
    </section>

    <section className="analysis-v2-central"><div className="page-width"><div className="analysis-v2-feature-heading reveal"><Eyebrow>{c.centralK}</Eyebrow><h2>{c.centralT}</h2><p>{c.centralP}</p></div><div className="analysis-v2-reading-flow reveal"><span>{language === "fr" ? "Question" : "Question"}</span><i><em /></i><strong>{c.centralMain}</strong><i><em /></i><span>{language === "fr" ? "Diagnostics" : "Diagnostics"}</span><i><em /></i><span>{language === "fr" ? "Interprétation" : "Interpretation"}</span></div><div className="analysis-v2-central-grid"><figure className="analysis-v2-central-main reveal"><img src={asset("app-previews/ordinations.png")} alt="" /><figcaption><b>01</b>{c.centralMain}</figcaption></figure><figure className="analysis-v2-central-side reveal"><img src={asset("app-previews/permanova_dispersion.png")} alt="" /><figcaption><b>02</b>{c.centralDiagnostic}</figcaption></figure><figure className="analysis-v2-central-side reveal"><img src={asset("app-previews/qualite_assignation_taxonomique.png")} alt="" /><figcaption><b>03</b>{c.centralQuality}</figcaption></figure></div><div className="analysis-v2-feature-cards">{c.centralItems.map(([title, text], index) => <article className="reveal" key={title}><span>{String(index + 1).padStart(2, "0")}</span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>

    <section className="analysis-v2-comparison"><div className="page-width"><div className="analysis-v2-feature-heading reveal"><Eyebrow>{c.compareK}</Eyebrow><h2>{c.compareT}</h2><p>{c.compareP}</p></div><div className="analysis-v2-comparison-stage reveal"><div className="analysis-v2-dataset-pool"><small>{language === "fr" ? "PROJET ACTIF" : "ACTIVE PROJECT"}</small><h3>{language === "fr" ? "Plusieurs datasets disponibles" : "Several available datasets"}</h3><div>{["A", "B", "C"].map((label, index) => <article key={label}><span>{label}</span><b>Dataset {label}</b><i style={{ width: `${74 - index * 12}%` }} /></article>)}</div></div><div className="analysis-v2-mode-switch"><span>→</span><b>{language === "fr" ? "Une interface, deux lectures" : "One interface, two readings"}</b><span>→</span></div><div className="analysis-v2-comparison-modes">{c.compareModes.map(([mode, title, text], index) => <article className={index === 1 ? "inter" : "intra"} key={mode}><header><span>{mode}</span><b>{title}</b></header><p>{text}</p><div className="analysis-v2-mode-visual">{index === 0 ? <>{["A", "B", "C"].map(label => <i key={label}><em>{label}</em><strong /></i>)}</> : <><i><em>A</em></i><i><em>B</em></i><i className="merged"><em>⇄</em><strong /></i></>}</div></article>)}</div></div><div className="analysis-v2-feature-cards">{c.compareCards.map(([title, text], index) => <article className="reveal" key={title}><span>{String(index + 1).padStart(2, "0")}</span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>

    <section className="analysis-v2-repro"><div className="page-width"><div className="analysis-v2-feature-heading reveal"><Eyebrow>{c.reproK}</Eyebrow><h2>{c.reproT}</h2><div className="analysis-v2-repro-intro"><span>↻</span><p>{c.reproP}</p></div></div><div className="analysis-v2-repro-flow reveal">{c.reproFlow.map((item, index) => <article key={item}><span>{String(index + 1).padStart(2, "0")}</span><b>{item}</b>{index < c.reproFlow.length - 1 && <i><em /></i>}</article>)}</div><div className="analysis-v2-repro-cards">{c.reproCards.map(([title, text], index) => <article className="reveal" key={title}><span>0{index + 1}</span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
  </main>;
}
