import { useState } from "react";
import type { Language } from "./content";

type FaqItem = [string, string, string, string];

function Eyebrow({ children }: { children: React.ReactNode }) {
  return <p className="eyebrow"><span />{children}</p>;
}

export default function FaqPage({ language }: { language: Language }) {
  const [filter, setFilter] = useState("all");
  const c = language === "fr" ? {
    k: "FAQ BarCodeR", title: "Toutes vos questions sur BarCodeR.", p: "Retrouvez toutes les réponses aux questions que vous vous posez à propos de l’utilisation de BarCodeR. Une documentation méthodologique et technique détaillée est également disponible directement dans l’application, depuis les onglets concernés.",
    topics: [["all", "Toutes"], ["installation", "Installation"], ["system", "Systèmes"], ["data", "Données"], ["openmeta", "OpenMetaBar"], ["projects", "Projets"], ["analysis", "Analyses"], ["repro", "Reproductibilité"], ["help", "Dépannage"]],
    filterLabel: "Filtrer les questions",
    items: [
      ["Faut-il installer R ou RStudio ?", "Non. La distribution autonome contient l’environnement nécessaire au lancement et à l’utilisation de BarCodeR.", "Installation", "installation"],
      ["Faut-il maintenir les packages R à jour ?", "Non. Les packages et leurs versions compatibles sont assemblés et testés lors de la fabrication de chaque distribution.", "Installation", "installation"],
      ["Comment installer BarCodeR ?", "Télécharger l’archive, la décompresser entièrement, puis double-cliquer sur l’application présente dans le dossier.", "Installation", "installation"],
      ["Des droits administrateur sont-ils nécessaires ?", "En principe non lorsque l’application est placée dans un dossier accessible en écriture. Une politique de sécurité institutionnelle peut toutefois demander l’intervention du service informatique.", "Installation", "installation"],
      ["Pourquoi Windows affiche-t-il parfois un avertissement ?", "Windows peut demander une confirmation pour un programme téléchargé. Vérifier l’origine officielle de l’archive avant de poursuivre.", "Installation", "installation"],
      ["Comment mettre BarCodeR à jour ?", "Télécharger la nouvelle archive et ouvrir la nouvelle version. R, RStudio et les packages ne sont pas mis à jour séparément.", "Installation", "installation"],
      ["Peut-on conserver plusieurs versions ?", "Oui. Des dossiers distincts permettent de conserver temporairement plusieurs distributions et de vérifier un projet avant de retirer l’ancienne version.", "Installation", "installation"],
      ["Sur quel système BarCodeR fonctionne-t-il directement ?", "La distribution autonome actuelle est destinée à Windows. Elle contient le lanceur, l’environnement R et les dépendances nécessaires à l’application.", "Systèmes", "system"],
      ["BarCodeR peut-il être utilisé sous macOS ?", "Il n’existe pas de distribution macOS native. L’utilisation nécessite une machine virtuelle exécutant Windows, dans laquelle l’archive BarCodeR est téléchargée, décompressée et lancée.", "Systèmes", "system"],
      ["BarCodeR peut-il être utilisé sous Linux ?", "Il n’existe pas de distribution Linux native. L’utilisation nécessite une machine virtuelle Windows disposant de suffisamment de mémoire, d’espace disque et de processeurs pour les analyses envisagées.", "Systèmes", "system"],
      ["Faut-il partager un dossier entre la machine virtuelle et le système hôte ?", "Ce n’est pas obligatoire, mais un dossier partagé facilite l’import des objets phyloseq et la récupération des exports. Les permissions de lecture et d’écriture doivent être vérifiées depuis Windows.", "Systèmes", "system"],
      ["Le téléchargement proposé sur ce site est-il actuellement l’application complète ?", "Non dans cette version de démonstration du site. Le bouton télécharge un petit fichier ZIP de test destiné uniquement à vérifier le fonctionnement du téléchargement. Il sera remplacé par la distribution officielle.", "Systèmes", "system"],
      ["Quels formats phyloseq peuvent être importés ?", "Les objets phyloseq compatibles peuvent être chargés depuis des fichiers .rds ou .RData. L’application vérifie ensuite leur structure.", "Données", "data"],
      ["Peut-on importer directement un fichier CSV, TSV, BIOM ou QZA ?", "Non dans Input data. L’import direct attend un objet phyloseq enregistré dans un fichier .rds ou .RData compatible. Les autres formats doivent d’abord être convertis et structurés en objet phyloseq.", "Données", "data"],
      ["Un objet phyloseq doit-il contenir toutes les composantes possibles ?", "Pas nécessairement. Certaines fonctions restent utilisables avec un objet partiel, mais leur disponibilité dépend des composantes présentes : table d’abondance, taxonomie, métadonnées, séquences ou arbre phylogénétique. Les contrôles d’import signalent les éléments disponibles et les incompatibilités détectées.", "Données", "data"],
      ["Que fait BarCodeR lorsqu’un objet ne respecte pas exactement ses conventions ?", "L’application vérifie la structure et peut appliquer les corrections automatiques prévues lorsqu’elles sont possibles. Les messages affichés doivent être relus avant d’utiliser le dataset, notamment si des noms, composantes ou correspondances ont été ajustés.", "Données", "data"],
      ["Peut-on commencer avec des fichiers FASTQ ?", "Oui. L’onglet OpenMetaBar prépare le traitement des séquences brutes et récupère l’objet phyloseq produit dans le projet.", "Données", "data"],
      ["Les données sont-elles envoyées en ligne ?", "Les objets phyloseq et les projets sont manipulés localement. Le traitement FASTQ peut utiliser l’infrastructure distante configurée pour OpenMetaBar.", "Données", "data"],
      ["Peut-on utiliser plusieurs datasets simultanément ?", "Oui. Un projet peut réunir plusieurs objets phyloseq, les analyser séparément et mobiliser plusieurs datasets dans les analyses inter-datasets compatibles.", "Données", "data"],
      ["Pourquoi un dataset volumineux ralentit-il l’application ?", "Le nombre d’échantillons, de taxons, de séquences et la méthode choisie influencent le temps de calcul. Une filtration scientifiquement justifiée peut réduire cette charge.", "Données", "data"],
      ["Quelles informations OpenMetaBar conserve-t-il sur un run ?", "OpenMetaBar attribue un Run ID et suit notamment le contexte, les paramètres, les ressources, les chemins, le Job ID, l’état Slurm, la chronologie et les fichiers détectés. Les détails disponibles dépendent du run, de ses métadonnées et de l’accès à l’infrastructure distante.", "OpenMetaBar", "openmeta"],
      ["Que se passe-t-il lorsqu’un phyloseq produit par OpenMetaBar est importé ?", "BarCodeR télécharge temporairement le fichier, recherche l’objet phyloseq, contrôle sa compatibilité, construit un nom unique et peut lui associer les paramètres de provenance disponibles pour le run avant de l’ajouter au projet actif.", "OpenMetaBar", "openmeta"],
      ["Le projet local contient-il tout le dossier du run OpenMetaBar ?", "Non. Le projet peut contenir le phyloseq importé et ses attributs de provenance, mais il ne copie pas automatiquement les FASTQ, les logs complets, le dossier work, les sorties Nextflow, les conteneurs, les bases ou le dossier distant du run. Ces éléments doivent être archivés séparément.", "OpenMetaBar", "openmeta"],
      ["Une fermeture de BarCodeR arrête-t-elle un calcul OpenMetaBar ?", "Non après la soumission au cluster. Le job Slurm continue indépendamment de la session locale. Il peut être retrouvé depuis l’historique après reconnexion au même environnement distant, sous réserve des chemins et droits d’accès.", "OpenMetaBar", "openmeta"],
      ["Peut-on importer un phyloseq provenant d’un run en échec ?", "Un phyloseq peut parfois avoir été produit avant l’étape ayant échoué. BarCodeR peut le détecter, mais son contenu et les journaux du run doivent être contrôlés avant toute analyse.", "OpenMetaBar", "openmeta"],
      ["Que contient un projet BarCodeR ?", "Un projet organise les datasets et conserve le contexte de travail : états des données, figures sauvegardées, historiques et code R lorsque disponible.", "Projets", "projects"],
      ["Comment transmettre un projet ?", "Exporter l’archive du projet puis la transmettre avec la version de BarCodeR utilisée. Le destinataire peut ainsi reprendre un environnement de travail structuré.", "Projets", "projects"],
      ["Un projet reste-t-il utilisable après une mise à jour ?", "Il est conçu pour être réutilisé. Conserver l’ancienne version jusqu’à l’ouverture et au contrôle d’une copie du projet dans la nouvelle distribution.", "Projets", "projects"],
      ["Une importation écrase-t-elle le dataset initial ?", "Les opérations d’édition et de filtration peuvent produire une nouvelle version nommée afin de conserver l’état initial dans le projet.", "Projets", "projects"],
      ["Quelle différence entre sauvegarder les datasets et exporter le projet complet ?", "L’export de données peut contenir un ou plusieurs objets phyloseq sans les figures ni les historiques. L’archive complète du projet vise à conserver le registre, le manifeste, les datasets, les figures et les historiques présents dans le dossier de travail.", "Projets", "projects"],
      ["Un projet importé s’ouvre-t-il automatiquement ?", "Non. L’import crée un nouveau projet. Il faut ensuite le sélectionner dans la liste des projets puis l’ouvrir pour charger ses datasets et recalculer les chemins propres aux modules.", "Projets", "projects"],
      ["Pourquoi une archive de projet peut-elle devenir volumineuse ?", "Les datasets, objets R intermédiaires, figures PNG, snapshots RDS, tableaux exportés et anciens historiques peuvent s’accumuler. Supprimer uniquement les historiques devenus inutiles et conserver des sauvegardes indépendantes avant tout nettoyage important.", "Projets", "projects"],
      ["Quelle différence entre Exploration et Analyse ?", "Exploration décrit les données et révèle leurs structures. Analyse regroupe les méthodes statistiques destinées à tester ou comparer explicitement ces structures.", "Analyses", "analysis"],
      ["Peut-on comparer plusieurs datasets ?", "Oui, lorsque la méthode accepte des objets compatibles ou des échantillons appariés. Les analyses intra-dataset restent également disponibles indépendamment.", "Analyses", "analysis"],
      ["Les figures sont-elles interactives ?", "Les modules compatibles permettent de modifier les paramètres, d’actualiser les résultats et de manipuler les visualisations avant leur sauvegarde.", "Analyses", "analysis"],
      ["À quoi sert MultiView ?", "MultiView rassemble les figures sauvegardées d’un projet et permet de les disposer, redimensionner et comparer dans une composition commune.", "Analyses", "analysis"],
      ["Que faut-il vérifier avant d’interpréter un résultat ?", "Consulter les diagnostics proposés, contrôler les prérequis de la méthode et replacer le résultat dans le plan expérimental et la qualité des données.", "Analyses", "analysis"],
      ["BarCodeR choisit-il automatiquement la bonne méthode scientifique ?", "Non. L’interface rend les méthodes et leurs paramètres accessibles, mais la formulation de la question, le plan expérimental, les prérequis, le choix de la méthode et l’interprétation restent sous la responsabilité de l’utilisateur.", "Analyses", "analysis"],
      ["Une figure affichée est-elle automatiquement sauvegardée ?", "Non. Un calcul terminé ou une figure visible à l’écran peut rester uniquement en mémoire. Il faut utiliser l’action de sauvegarde du module après avoir contrôlé le calcul et le rendu pour créer un historique persistant.", "Analyses", "analysis"],
      ["Pourquoi une figure sauvegardée n’apparaît-elle pas dans MultiView ?", "MultiView affiche les types compatibles présents dans le projet courant. Selon le module, le PNG doit être accompagné du snapshot RDS portant le même nom de base. Actualiser la bibliothèque et vérifier le projet actif ainsi que la sauvegarde de la figure.", "Analyses", "analysis"],
      ["Comment retrouver les paramètres d’une figure ?", "Une figure sauvegardée reste associée au dataset, à sa version, aux paramètres et aux traces disponibles dans le projet.", "Reproductibilité", "repro"],
      ["Le code R est-il disponible pour toutes les actions ?", "Il est conservé lorsque le module peut le générer. Certaines actions d’interface ou visualisations ne produisent pas nécessairement un script complet.", "Reproductibilité", "repro"],
      ["Comment citer BarCodeR ?", "Utiliser la page Citation, sélectionner le format bibliographique adapté et indiquer la version réellement utilisée dans le travail.", "Reproductibilité", "repro"],
      ["Que peut contenir le snapshot d’une analyse ?", "Selon le module, un snapshot peut contenir les paramètres, résultats, figures, tableaux, journaux, données nécessaires à la reproduction, graine aléatoire et versions de packages. Le contenu exact dépend de la méthode et de l’action de sauvegarde.", "Reproductibilité", "repro"],
      ["Peut-on comparer plusieurs essais d’une même analyse ?", "Oui. En sauvegardant chaque essai sous une identité distincte, il devient possible de confronter les paramètres, les diagnostics et les figures sans remplacer silencieusement le résultat précédent.", "Reproductibilité", "repro"],
      ["Une connexion internet est-elle obligatoire ?", "Non pour les analyses locales. Elle peut être nécessaire pour télécharger l’application, consulter une ressource externe ou utiliser l’infrastructure OpenMetaBar.", "Dépannage", "help"],
      ["Que faire si l’application ne démarre pas ?", "Vérifier que l’archive est entièrement décompressée, que le dossier est complet et accessible, puis retélécharger la même version si nécessaire.", "Dépannage", "help"],
      ["Que faire si l’interface semble figée pendant un calcul ?", "Attendre la fin du calcul, vérifier les ressources de la machine et tester un sous-ensemble ou une filtration adaptée avant de relancer une analyse lourde.", "Dépannage", "help"],
      ["Où trouver la documentation complète ?", "La documentation méthodologique et technique est intégrée à BarCodeR. Elle détaille les entrées, paramètres, sorties, limites et situations de dépannage de chaque onglet. Elle doit être consultée pour les choix précis qui dépassent cette FAQ.", "Dépannage", "help"],
      ["Que faire si l’import d’un phyloseq échoue ?", "Vérifier l’extension du fichier, la présence effective d’un objet phyloseq, sa lisibilité, ses composantes et les messages de compatibilité. Tester si possible avec un objet public proposé dans les tutoriels afin de distinguer un problème de fichier d’un problème d’installation.", "Dépannage", "help"],
      ["Comment signaler un problème de manière utile ?", "Noter la version de BarCodeR, le système Windows utilisé, l’onglet concerné, l’action effectuée, les paramètres essentiels, le message affiché et, si possible, fournir un objet public ou anonymisé permettant de reproduire le problème.", "Dépannage", "help"]
    ] as FaqItem[]
  } : {
    k: "BarCodeR FAQ", title: "All your questions about BarCodeR.", p: "Find detailed answers to your questions about using BarCodeR. Comprehensive methodological and technical documentation is also available directly inside the application from the relevant tabs.",
    topics: [["all", "All"], ["installation", "Installation"], ["system", "Systems"], ["data", "Data"], ["openmeta", "OpenMetaBar"], ["projects", "Projects"], ["analysis", "Analyses"], ["repro", "Reproducibility"], ["help", "Troubleshooting"]],
    filterLabel: "Filter questions",
    items: [
      ["Do I need to install R or RStudio?", "No. The standalone distribution contains the environment required to launch and use BarCodeR.", "Installation", "installation"],
      ["Do I need to maintain R packages?", "No. Compatible package versions are assembled and tested when each distribution is built.", "Installation", "installation"],
      ["How do I install BarCodeR?", "Download the archive, extract it completely, then double-click the application inside the folder.", "Installation", "installation"],
      ["Are administrator rights required?", "Usually not when the application is placed in a writable folder. Institutional security policies may still require IT assistance.", "Installation", "installation"],
      ["Why can Windows display a warning?", "Windows may ask for confirmation before running downloaded software. Check that the archive came from the official source first.", "Installation", "installation"],
      ["How do I update BarCodeR?", "Download the new archive and open the new version. R, RStudio and packages are not updated separately.", "Installation", "installation"],
      ["Can I keep several versions?", "Yes. Separate folders can retain several distributions while a project is checked before the previous version is removed.", "Installation", "installation"],
      ["Which system runs BarCodeR directly?", "The current standalone distribution is intended for Windows. It contains the launcher, R environment and dependencies required by the application.", "Systems", "system"],
      ["Can BarCodeR be used on macOS?", "There is no native macOS distribution. A Windows virtual machine is required, and the BarCodeR archive must be downloaded, extracted and launched inside that virtual machine.", "Systems", "system"],
      ["Can BarCodeR be used on Linux?", "There is no native Linux distribution. A Windows virtual machine with enough memory, disk space and processors for the intended analyses is required.", "Systems", "system"],
      ["Should a folder be shared between the virtual machine and host system?", "It is not required, but a shared folder makes phyloseq imports and output retrieval easier. Read and write permissions must be checked from Windows.", "Systems", "system"],
      ["Is the current website download the complete application?", "No, not in this demonstration build of the website. The button downloads a small test ZIP used only to check that downloads work. It will later be replaced by the official distribution.", "Systems", "system"],
      ["Which phyloseq formats can be imported?", "Compatible phyloseq objects can be loaded from .rds or .RData files. The application then checks their structure.", "Data", "data"],
      ["Can CSV, TSV, BIOM or QZA files be imported directly?", "No, not through Input data. Direct import expects a compatible phyloseq object stored in an .rds or .RData file. Other formats must first be converted and structured as a phyloseq object.", "Data", "data"],
      ["Must a phyloseq object contain every possible component?", "Not necessarily. Some features remain available with a partial object, but availability depends on its abundance table, taxonomy, metadata, sequences and phylogenetic tree. Import checks report available components and detected incompatibilities.", "Data", "data"],
      ["What happens when an object does not exactly follow BarCodeR conventions?", "The application checks its structure and may apply supported automatic corrections. Review displayed messages before using the dataset, especially when names, components or correspondences have been adjusted.", "Data", "data"],
      ["Can I start from FASTQ files?", "Yes. The OpenMetaBar tab prepares raw-sequence processing and retrieves the resulting phyloseq object into the project.", "Data", "data"],
      ["Are data sent online?", "Phyloseq objects and projects are handled locally. FASTQ processing may use the remote infrastructure configured for OpenMetaBar.", "Data", "data"],
      ["Can several datasets be used simultaneously?", "Yes. One project can collect several phyloseq objects, analyse them separately and use several datasets in compatible between-dataset analyses.", "Data", "data"],
      ["Why can a large dataset slow the application?", "Sample, taxon and sequence counts and the selected method affect calculation time. Scientifically justified filtering can reduce the load.", "Data", "data"],
      ["What run information does OpenMetaBar retain?", "OpenMetaBar assigns a Run ID and can track context, settings, resources, paths, Job ID, Slurm status, timeline and detected files. Available details depend on run metadata and access to the remote infrastructure.", "OpenMetaBar", "openmeta"],
      ["What happens when a phyloseq object generated by OpenMetaBar is imported?", "BarCodeR temporarily downloads the file, searches for a phyloseq object, checks compatibility, builds a unique name and may associate available run provenance before adding it to the active project.", "OpenMetaBar", "openmeta"],
      ["Does the local project contain the whole OpenMetaBar run folder?", "No. The project may contain the imported phyloseq object and provenance attributes, but FASTQ files, full logs, the work directory, Nextflow outputs, containers, databases and the remote run folder are not copied automatically. Archive them separately.", "OpenMetaBar", "openmeta"],
      ["Does closing BarCodeR stop an OpenMetaBar calculation?", "Not after submission to the cluster. The Slurm job continues independently of the local session and may be recovered from history after reconnecting to the same remote environment, subject to paths and permissions.", "OpenMetaBar", "openmeta"],
      ["Can a phyloseq object from a failed run be imported?", "A phyloseq object may have been produced before the failing step. BarCodeR can sometimes detect it, but its contents and run logs must be reviewed before analysis.", "OpenMetaBar", "openmeta"],
      ["What does a BarCodeR project contain?", "A project organises datasets and retains working context: data states, saved figures, histories and R code when available.", "Projects", "projects"],
      ["How can a project be shared?", "Export the project archive and share it with the BarCodeR version used so another person can resume a structured workspace.", "Projects", "projects"],
      ["Will a project work after an update?", "It is designed to be reusable. Keep the previous version until a copy of the project has been opened and checked in the new distribution.", "Projects", "projects"],
      ["Does an import overwrite the original dataset?", "Editing and filtering operations can produce a named new version so the initial state remains available in the project.", "Projects", "projects"],
      ["What is the difference between exporting datasets and exporting a complete project?", "A data export can contain one or several phyloseq objects without figures or histories. A complete project archive aims to retain the registry, manifest, datasets, figures and histories present in the workspace.", "Projects", "projects"],
      ["Does an imported project open automatically?", "No. Import creates a new project. Select it from the project list and open it to load datasets and recalculate module-specific paths.", "Projects", "projects"],
      ["Why can a project archive become large?", "Datasets, intermediate R objects, PNG figures, RDS snapshots, exported tables and old histories can accumulate. Remove only histories that are no longer needed and keep independent backups before major cleanup.", "Projects", "projects"],
      ["What is the difference between Exploration and Analysis?", "Exploration describes data and reveals structures. Analysis gathers statistical methods that explicitly test or compare those structures.", "Analyses", "analysis"],
      ["Can several datasets be compared?", "Yes, when a method accepts compatible objects or paired samples. Within-dataset analyses remain independently available.", "Analyses", "analysis"],
      ["Are figures interactive?", "Compatible modules allow settings to be changed, results to update and visualisations to be manipulated before saving.", "Analyses", "analysis"],
      ["What is MultiView for?", "MultiView gathers saved project figures and lets them be arranged, resized and compared in one composition.", "Analyses", "analysis"],
      ["What should be checked before interpreting a result?", "Review available diagnostics, method requirements, experimental design and data quality.", "Analyses", "analysis"],
      ["Does BarCodeR automatically choose the correct scientific method?", "No. The interface makes methods and settings accessible, but the scientific question, experimental design, prerequisites, method choice and interpretation remain the user's responsibility.", "Analyses", "analysis"],
      ["Is a displayed figure saved automatically?", "No. A completed calculation or visible figure may exist only in memory. Use the module's save action after checking the calculation and rendering to create a persistent history entry.", "Analyses", "analysis"],
      ["Why is a saved figure missing from MultiView?", "MultiView displays compatible types in the current project. Depending on the module, the PNG must be paired with an RDS snapshot sharing the same base name. Refresh the library and check the active project and figure save operation.", "Analyses", "analysis"],
      ["How can the parameters behind a figure be found?", "A saved figure remains associated with the dataset, its version, parameters and available traces in the project.", "Reproducibility", "repro"],
      ["Is R code available for every action?", "It is retained when a module can generate it. Some interface actions or visualisations may not produce a complete script.", "Reproducibility", "repro"],
      ["How should BarCodeR be cited?", "Use the Citation page, select the appropriate bibliographic format and report the version actually used.", "Reproducibility", "repro"],
      ["What can an analysis snapshot contain?", "Depending on the module, a snapshot may contain settings, results, figures, tables, logs, reproduction data, a random seed and package versions. Exact contents depend on the method and save action.", "Reproducibility", "repro"],
      ["Can several attempts of the same analysis be compared?", "Yes. Saving each attempt under a distinct identity makes it possible to compare settings, diagnostics and figures without silently replacing the previous result.", "Reproducibility", "repro"],
      ["Is an internet connection required?", "Not for local analyses. It may be needed to download the application, open an external resource or use OpenMetaBar infrastructure.", "Troubleshooting", "help"],
      ["What if the application does not start?", "Check that the archive was fully extracted, that the folder is complete and accessible, then download the same version again if needed.", "Troubleshooting", "help"],
      ["What if the interface appears frozen during a calculation?", "Wait for the calculation, check machine resources and try a subset or suitable filtering before relaunching a heavy analysis.", "Troubleshooting", "help"],
      ["Where can the complete documentation be found?", "Methodological and technical documentation is built into BarCodeR. It details inputs, settings, outputs, limitations and troubleshooting for each tab and should be consulted for choices beyond this FAQ.", "Troubleshooting", "help"],
      ["What if a phyloseq import fails?", "Check the file extension, confirm it contains a readable phyloseq object, review its components and compatibility messages, and test a public tutorial object to distinguish a file problem from an installation problem.", "Troubleshooting", "help"],
      ["How can a useful issue report be prepared?", "Record the BarCodeR version, Windows system, relevant tab, action, essential settings and displayed message and, where possible, provide a public or anonymised object that reproduces the problem.", "Troubleshooting", "help"]
    ] as FaqItem[]
  };
  const visibleItems = filter === "all" ? c.items : c.items.filter(item => item[3] === filter);

  return <main className="faq-page">
    <section className="faq-page-hero"><div className="page-width"><div className="installer-v2-faq-orbit" aria-hidden="true"><span>?</span><i /><i /></div><header><Eyebrow>{c.k}</Eyebrow><h1>{c.title}</h1><p>{c.p}</p></header></div></section>
    <section className="faq-page-content"><div className="page-width"><div className="installer-v2-faq-topics" role="group" aria-label={c.filterLabel}>{c.topics.map(([value, label]) => <button type="button" className={filter === value ? "active" : ""} aria-pressed={filter === value} onClick={() => setFilter(value)} key={value}>{label}</button>)}</div><div className="installer-v2-faq-list faq-page-grid">{visibleItems.map(([question, answer, tag], index) => <details className="reveal visible" open={index === 0} key={question}><summary><span>{String(index + 1).padStart(2, "0")}</span><div><small>{tag}</small><b>{question}</b></div><i aria-hidden="true">+</i></summary><p>{answer}</p></details>)}</div></div></section>
  </main>;
}
